### ISSUE TITLE
Asking for some advice on KITTI 3D det usage.

### ISSUE THREAD

**Issue by Cc-Hy** [cogaplex-bts/bts#119]
HELLO, good job!
I'm trying to pick one of your trained model to use in the KITTI 3D detection task in which I'll take in a image and use your model to generate a depth prediction map ,downsample it by 4 times then do 3D detection based on it . To get rid of overfitting, i'd like to fix your depth prediction model, and train the net after that. BUT I'm not very familiar with your net, so i'm asking for some advice. Here i have some questions:
1.The images in 3d det task are also part of the KITTI raw data but may be a little different. The size may be around 1242 * 375 e.g.and the cared depth is within 40m, and i want get a depth map of size 311 * 91.  so can i directly use your net on these images?
2. I plan to use your net by creating the model, loading the pre-trained parameters and do the forward process. so i think i need not many lines of your code, by using
`model = BtsModel(params=args)`
`lpg8x8, lpg4x4, lpg2x2, reduc1x1, depth_est = model(image, focal)`
`subsequent_results = my_model(depth_est, image)`
However, i found there is a 'focal' in model forward args, and i have no idea on it, I only use a image as input. Can i avoid using it?

**Comment by Cc-Hy** [comment]
When i directly apply the model to the image with shape 1242*375, error occurs.

![image](https://user-images.githubusercontent.com/82150240/131498384-0a23684d-43d6-4c04-928c-a2781ad51f17.png)

Because 375 is not a multiple of 16, and the two branch got a different channel size in the 16 downsample module.

**Comment by cogaplex-bts** [comment]
@Cc-Hy Thanks for your interest in our work. Let me briefly answer your questions.
1. Image height and width should be multiples of 32 because of downsampling in our encoder.
2. "Focal" is the focal length of your camera which determines imaging geometry. If you train and test on images all from the same camera, you don't have to specify correct value for it. But if this is not the case, you need to get the correct value.
