### ISSUE TITLE
Download link for bts_eigen_v2_pytorch_densenet161.zip not working

### ISSUE THREAD

**Issue by DaneSpaeth** [cogaplex-bts/bts#44]
Hi @cogaplex-bts , thank you very much for your great work.
Unfortunately, I don't seem to be able to download the bts_eigen_v2_pytorch_densenet161.zip files with the link you give in your pytorch readme.
(https://cogaplex-bts.s3.ap-northeast-2.amazonaws.com/bts_eigen_v2_pytorch_densenet161.zip)

Is this link outdated and is the data otherwise available?

Thank you,
Dane

**Comment by cogaplex-bts** [comment]
@DaneSpaeth Sorry for the inconvenience. It was not set as public by accident. Now it works.

**Comment by DaneSpaeth** [comment]
Thanks for the quick answer! The download works now.

**Comment by starrismlx** [comment]
Hi @cogaplex-bts , thank you very much for your great work.
Unfortunately, I don't seem to be able to download the bts_eigen_v2_pytorch_densenet161.zip files with the link you give in your pytorch readme.
wget https://cogaplex-bts.s3.ap-northeast-2.amazonaws.com/bts_nyu_v2_pytorch_densenet161.zip

Is this link outdated and is the data otherwise available?

Thank you,
Amber
